//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBuggyService")]
    public interface IBuggyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuggyService/ThrowsException", ReplyAction="http://tempuri.org/IBuggyService/ThrowsExceptionResponse")]
        string ThrowsException(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuggyService/DoesNotRespond", ReplyAction="http://tempuri.org/IBuggyService/DoesNotRespondResponse")]
        string DoesNotRespond(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuggyServiceChannel : WcfServiceClient.ServiceReference1.IBuggyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuggyServiceClient : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.IBuggyService>, WcfServiceClient.ServiceReference1.IBuggyService {
        
        public BuggyServiceClient() {
        }
        
        public BuggyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuggyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuggyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuggyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ThrowsException(int value) {
            return base.Channel.ThrowsException(value);
        }
        
        public string DoesNotRespond(int value) {
            return base.Channel.DoesNotRespond(value);
        }
    }
}
